main_account = Account.find_or_create_by(name: "Main Account", main_account: true)
fund_1 = Account.find_or_create_by(name: "Treat Yourself", main_account: false)
fund_2 = Account.find_or_create_by(name: "Give to Others", main_account: false)
fund_3 = Account.find_or_create_by(name: "Big Purchases", main_account: false)
fund_4 = Account.find_or_create_by(name: "Savings Fund", main_account: false)

transaction_1 = Transaction.find_or_create_by(counterparty: "Capital One", date: "June 3, 2019", amount: 3000, account_id: 1, parent_id: 0, debit: true, percentage: 10)
transaction_2 = Transaction.find_or_create_by(counterparty: "Capital One", date: "June 3, 2019", amount: 300, account_id: 2, parent_id: 1, debit: true, percentage: 10)
transaction_3 = Transaction.find_or_create_by(counterparty: "Capital One", date: "June 3, 2019", amount: 300, account_id: 3, parent_id: 1, debit: true, percentage: 10)
transaction_4 = Transaction.find_or_create_by(counterparty: "Capital One", date: "June 3, 2019", amount: 300, account_id: 4, parent_id: 1, debit: true, percentage: 10)
transaction_5 = Transaction.find_or_create_by(counterparty: "Capital One", date: "June 3, 2019", amount: 300, account_id: 5, parent_id: 1, debit: true, percentage: 10)

transaction_6 = Transaction.find_or_create_by(counterparty: "Whole Foods", date: "June 5, 2019", amount: 50, account_id: 1, parent_id: 0, debit: false, percentage: 0)
transaction_7 = Transaction.find_or_create_by(counterparty: "Spa", date: "June 6, 2019", amount: 75, account_id: 2, parent_id: 0, debit: false, percentage: 0)
transaction_8 = Transaction.find_or_create_by(counterparty: "Rothy's", date: "June 8, 2019", amount: 125, account_id: 2, parent_id: 0, debit: false, percentage: 0)
transaction_9 = Transaction.find_or_create_by(counterparty: "Ellwood's", date: "June 11, 2019", amount: 30, account_id: 1, parent_id: 0, debit: false, percentage: 0)
transaction_10 = Transaction.find_or_create_by(counterparty: "Gas Station", date: "June 12, 2019", amount: 25, account_id: 1, parent_id: 0, debit: false, percentage: 0)
