main_account = Account.create(name: "Main Account", main_account: true)
fund_1 = Account.create(name: "Treat Yourself", main_account: false)
fund_2 = Account.create(name: "Give to Others", main_account: false)
fund_3 = Account.create(name: "Big Purchases", main_account: false)
fund_4 = Account.create(name: "Savings Fund", main_account: false)
